#!/usr/bin/env bash

versionFile=versionCheck.txt
brokenFile=broken_quiet.txt
url=http://users.pacbsd.org/~repo/repo-report/current

fetch -q ${url}/${brokenFile} -o /tmp/${brokenFile}
fetch -q ${url}/${versionFile} -o /tmp/${versionFile}

green=$(tput setaf 2)
red=$(tput setaf 1)
normal=$(tput sgr0)

check_broken() {
	local _pkg="$1"
	local _prov="$1"
	if (is_a_provide -v "$_prov"); then
		_prov=$(is_a_provide -p "$_prov" | head -1)
		if ( grep -q "${_prov}$" /tmp/${brokenFile} ); then
			echo "${_pkg} is provided by ${_prov} which is broken"
		fi
	else
		if ( grep -q "${_pkg}$" /tmp/${brokenFile} ); then
			echo "${_pkg} is broken."
		fi
	fi

}

check_version() {
	local _pkg="$1"
	local _prov="$1"
        if (is_a_provide -v "$_prov"); then
		_prov=$(is_a_provide -p "$_prov" | head -1)
		if ( grep -q "${_prov}$" /tmp/${versionFile} ); then
			echo "${_pkg} is provided by ${_prov} which is outdated"
		fi
	else
		if ( grep -q "/${_pkg} " /tmp/${versionFile} ); then
			echo "${_pkg} is outdated."
		fi
	fi
}

_msg() {
	local mesg=$1; shift
	echo "${green}#################################${normal}"
	echo "${red}${mesg}${normal}: ${depends[@]}"
	echo "${green}#################################${normal}"
}

_msg2() {
        local mesg=$1; shift
        echo "${green}#################################${normal}"
        echo "${red}${mesg}${normal}: ${makedepends[@]}"
        echo "${green}#################################${normal}"
}


if [ ! -f PKGBUILD ];then
	echo "No PKGBUILD found"
else
	source PKGBUILD
	_msg "depends"
	for dep in ${depends[@]}; do
		check_broken "${dep%%[<>=]*}"
	done

	for dep in ${depends[@]}; do
		check_version "${dep%%[<>=]*}"
	done

	_msg2 "makedepends"

        for dep in ${makedepends[@]}; do
                check_broken "${dep%%[<>=]*}"
        done

	for dep in ${makedepends[@]}; do
		check_version "${dep%%[<>=]*}"
	done

	unset depends makedepends

fi
